"""add_has_jellyseerr_account_to_user_nicknames

Revision ID: 2df76fc5982a
Revises: fe6cb204727f
Create Date: 2026-01-16 18:48:30.547820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df76fc5982a'
down_revision: Union[str, None] = 'fe6cb204727f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default=False to handle existing rows
    op.add_column('user_nicknames', sa.Column('has_jellyseerr_account', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_nicknames', 'has_jellyseerr_account')
    # ### end Alembic commands ###
