"""add_jellyseerr_request_whitelist_table

Revision ID: 1ec02b9e9cad
Revises: dd160c1475ae
Create Date: 2026-01-14 18:37:30.386803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec02b9e9cad'
down_revision: Union[str, None] = 'dd160c1475ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jellyseerr_request_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyseerr_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jellyseerr_request_whitelist_jellyseerr_id'), 'jellyseerr_request_whitelist', ['jellyseerr_id'], unique=False)
    op.create_index(op.f('ix_jellyseerr_request_whitelist_user_id'), 'jellyseerr_request_whitelist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jellyseerr_request_whitelist_user_id'), table_name='jellyseerr_request_whitelist')
    op.drop_index(op.f('ix_jellyseerr_request_whitelist_jellyseerr_id'), table_name='jellyseerr_request_whitelist')
    op.drop_table('jellyseerr_request_whitelist')
    # ### end Alembic commands ###
