"""add_episode_language_exempt_table

Revision ID: 6033f4a29b44
Revises: 6443d327371b
Create Date: 2026-01-23 02:01:39.637019

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6033f4a29b44"
down_revision: str | None = "6443d327371b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episode_language_exempt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("jellyfin_id", sa.String(length=100), nullable=False),
        sa.Column("series_name", sa.String(length=500), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("episode_name", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "jellyfin_id",
            "season_number",
            "episode_number",
            name="uq_episode_exempt",
        ),
    )
    op.create_index(
        op.f("ix_episode_language_exempt_jellyfin_id"),
        "episode_language_exempt",
        ["jellyfin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_language_exempt_user_id"),
        "episode_language_exempt",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_episode_language_exempt_user_id"),
        table_name="episode_language_exempt",
    )
    op.drop_index(
        op.f("ix_episode_language_exempt_jellyfin_id"),
        table_name="episode_language_exempt",
    )
    op.drop_table("episode_language_exempt")
    # ### end Alembic commands ###
