"""add_recently_available_days_to_user_settings

Revision ID: 70631b1ac6c1
Revises: b6f33798b626
Create Date: 2026-01-15 19:21:22.174442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70631b1ac6c1'
down_revision: Union[str, None] = 'b6f33798b626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('recently_available_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'recently_available_days')
    # ### end Alembic commands ###
