"""add_large_content_whitelist

Revision ID: 29f2eb687fce
Revises: 98891c396773
Create Date: 2026-01-20 09:40:48.406745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f2eb687fce'
down_revision: Union[str, None] = '98891c396773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('large_content_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_large_content_whitelist_jellyfin_id'), 'large_content_whitelist', ['jellyfin_id'], unique=False)
    op.create_index(op.f('ix_large_content_whitelist_user_id'), 'large_content_whitelist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_large_content_whitelist_user_id'), table_name='large_content_whitelist')
    op.drop_index(op.f('ix_large_content_whitelist_jellyfin_id'), table_name='large_content_whitelist')
    op.drop_table('large_content_whitelist')
    # ### end Alembic commands ###
