"""add_large_season_size_gb_to_user_settings

Revision ID: 208afe3608f2
Revises: 3b40c1f59b06
Create Date: 2026-01-15 23:02:19.720855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208afe3608f2'
down_revision: Union[str, None] = '3b40c1f59b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('large_season_size_gb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'large_season_size_gb')
    # ### end Alembic commands ###
