"""add_title_fr_to_cached_jellyseerr_requests

Revision ID: 3426eda50cac
Revises: ea2cb0fab70e
Create Date: 2026-01-16 19:25:31.236108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3426eda50cac'
down_revision: Union[str, None] = 'ea2cb0fab70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_jellyseerr_requests', sa.Column('title_fr', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_jellyseerr_requests', 'title_fr')
    # ### end Alembic commands ###
