"""add_radarr_sonarr_settings

Revision ID: 05394614200c
Revises: fa6f8809cb38
Create Date: 2026-01-14 22:22:51.853268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05394614200c'
down_revision: Union[str, None] = 'fa6f8809cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('radarr_server_url', sa.String(length=500), nullable=True))
    op.add_column('user_settings', sa.Column('radarr_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('sonarr_server_url', sa.String(length=500), nullable=True))
    op.add_column('user_settings', sa.Column('sonarr_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'sonarr_api_key_encrypted')
    op.drop_column('user_settings', 'sonarr_server_url')
    op.drop_column('user_settings', 'radarr_api_key_encrypted')
    op.drop_column('user_settings', 'radarr_server_url')
    # ### end Alembic commands ###
