"""add_show_unreleased_requests_to_user_settings

Revision ID: fa6f8809cb38
Revises: 1ec02b9e9cad
Create Date: 2026-01-14 19:15:06.490521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6f8809cb38'
down_revision: Union[str, None] = '1ec02b9e9cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('show_unreleased_requests', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'show_unreleased_requests')
    # ### end Alembic commands ###
