"""add_title_language_to_user_settings

Revision ID: ea2cb0fab70e
Revises: 2df76fc5982a
Create Date: 2026-01-16 19:12:23.694930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2cb0fab70e'
down_revision: Union[str, None] = '2df76fc5982a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('title_language', sa.String(length=2), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'title_language')
    # ### end Alembic commands ###
