"""add_sync_progress_fields

Revision ID: 3b40c1f59b06
Revises: 26f93eb2880e
Create Date: 2026-01-15 20:24:22.733199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b40c1f59b06'
down_revision: Union[str, None] = '26f93eb2880e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_status', sa.Column('current_step', sa.String(length=100), nullable=True))
    op.add_column('sync_status', sa.Column('total_steps', sa.Integer(), nullable=True))
    op.add_column('sync_status', sa.Column('current_step_progress', sa.Integer(), nullable=True))
    op.add_column('sync_status', sa.Column('current_step_total', sa.Integer(), nullable=True))
    op.add_column('sync_status', sa.Column('current_user_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_status', 'current_user_name')
    op.drop_column('sync_status', 'current_step_total')
    op.drop_column('sync_status', 'current_step_progress')
    op.drop_column('sync_status', 'total_steps')
    op.drop_column('sync_status', 'current_step')
    # ### end Alembic commands ###
