"""add_release_date_to_cached_jellyseerr_requests

Revision ID: dd160c1475ae
Revises: 782c8928d5cd
Create Date: 2026-01-14 18:23:06.537286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd160c1475ae'
down_revision: Union[str, None] = '782c8928d5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_jellyseerr_requests', sa.Column('release_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_jellyseerr_requests', 'release_date')
    # ### end Alembic commands ###
