"""add_largest_season_size_bytes_to_cached_media_items

Revision ID: fe6cb204727f
Revises: 208afe3608f2
Create Date: 2026-01-15 23:15:52.548816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6cb204727f'
down_revision: Union[str, None] = '208afe3608f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_media_items', sa.Column('largest_season_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_media_items', 'largest_season_size_bytes')
    # ### end Alembic commands ###
