"""add_user_nicknames_table

Revision ID: 26f93eb2880e
Revises: 70631b1ac6c1
Create Date: 2026-01-15 19:41:08.030728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f93eb2880e'
down_revision: Union[str, None] = '70631b1ac6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_nicknames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyseerr_username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'jellyseerr_username', name='uq_user_nickname')
    )
    op.create_index(op.f('ix_user_nicknames_user_id'), 'user_nicknames', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nicknames_user_id'), table_name='user_nicknames')
    op.drop_table('user_nicknames')
    # ### end Alembic commands ###
