"""add_language_check_fields_to_cached_media_items

Revision ID: 6443d327371b
Revises: 54b0e03433c5
Create Date: 2026-01-23 01:39:14.559373

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6443d327371b"
down_revision: str | None = "54b0e03433c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cached_media_items",
        sa.Column("language_check_result", sa.JSON(), nullable=True),
    )
    op.add_column(
        "cached_media_items",
        sa.Column("problematic_episodes", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cached_media_items", "problematic_episodes")
    op.drop_column("cached_media_items", "language_check_result")
    # ### end Alembic commands ###
