"""add_ultra_api_settings_to_user_settings

Revision ID: 30dd116f11f8
Revises: 29f2eb687fce
Create Date: 2026-01-22 08:17:16.427079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dd116f11f8'
down_revision: Union[str, None] = '29f2eb687fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('ultra_api_url', sa.String(length=500), nullable=True))
    op.add_column('user_settings', sa.Column('ultra_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ultra_api_key_encrypted')
    op.drop_column('user_settings', 'ultra_api_url')
    # ### end Alembic commands ###
