"""add_ultra_stats_columns_to_user_settings

Revision ID: 54b0e03433c5
Revises: 26a3b23ff8ca
Create Date: 2026-01-22 08:48:14.185944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b0e03433c5'
down_revision: Union[str, None] = '26a3b23ff8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('ultra_free_storage_gb', sa.Float(), nullable=True))
    op.add_column('user_settings', sa.Column('ultra_traffic_available_percent', sa.Float(), nullable=True))
    op.add_column('user_settings', sa.Column('ultra_last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ultra_last_synced_at')
    op.drop_column('user_settings', 'ultra_traffic_available_percent')
    op.drop_column('user_settings', 'ultra_free_storage_gb')
    # ### end Alembic commands ###
