"""add_jellyseerr_media_id_to_cached_requests

Revision ID: eb34d38ca967
Revises: 3fe4b091117b
Create Date: 2026-01-15 13:12:35.252939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb34d38ca967'
down_revision: Union[str, None] = '3fe4b091117b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_jellyseerr_requests', sa.Column('jellyseerr_media_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cached_jellyseerr_requests_jellyseerr_media_id'), 'cached_jellyseerr_requests', ['jellyseerr_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cached_jellyseerr_requests_jellyseerr_media_id'), table_name='cached_jellyseerr_requests')
    op.drop_column('cached_jellyseerr_requests', 'jellyseerr_media_id')
    # ### end Alembic commands ###
