"""add_theme_preference_to_user_settings

Revision ID: 3fe4b091117b
Revises: 05394614200c
Create Date: 2026-01-15 01:42:19.261511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe4b091117b'
down_revision: Union[str, None] = '05394614200c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('theme_preference', sa.String(length=10), nullable=False, server_default='system'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'theme_preference')
    # ### end Alembic commands ###
