"""add_ultra_warning_thresholds_to_user_settings

Revision ID: 26a3b23ff8ca
Revises: 30dd116f11f8
Create Date: 2026-01-22 08:29:46.375096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a3b23ff8ca'
down_revision: Union[str, None] = '30dd116f11f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('ultra_storage_warning_gb', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('ultra_traffic_warning_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ultra_traffic_warning_percent')
    op.drop_column('user_settings', 'ultra_storage_warning_gb')
    # ### end Alembic commands ###
