"""initial_schema

Revision ID: 782c8928d5cd
Revises: 
Create Date: 2026-01-14 10:07:37.950550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782c8928d5cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cached_jellyseerr_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyseerr_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('created_at_source', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_jellyseerr_requests_jellyseerr_id'), 'cached_jellyseerr_requests', ['jellyseerr_id'], unique=False)
    op.create_index(op.f('ix_cached_jellyseerr_requests_user_id'), 'cached_jellyseerr_requests', ['user_id'], unique=False)
    op.create_table('cached_media_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('production_year', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.String(length=50), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('last_played_date', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_media_items_jellyfin_id'), 'cached_media_items', ['jellyfin_id'], unique=False)
    op.create_index(op.f('ix_cached_media_items_user_id'), 'cached_media_items', ['user_id'], unique=False)
    op.create_table('content_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_whitelist_jellyfin_id'), 'content_whitelist', ['jellyfin_id'], unique=False)
    op.create_index(op.f('ix_content_whitelist_user_id'), 'content_whitelist', ['user_id'], unique=False)
    op.create_table('french_only_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_french_only_whitelist_jellyfin_id'), 'french_only_whitelist', ['jellyfin_id'], unique=False)
    op.create_index(op.f('ix_french_only_whitelist_user_id'), 'french_only_whitelist', ['user_id'], unique=False)
    op.create_table('language_exempt_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_exempt_whitelist_jellyfin_id'), 'language_exempt_whitelist', ['jellyfin_id'], unique=False)
    op.create_index(op.f('ix_language_exempt_whitelist_user_id'), 'language_exempt_whitelist', ['user_id'], unique=False)
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_sync_started', sa.DateTime(), nullable=True),
    sa.Column('last_sync_completed', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('media_items_count', sa.Integer(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_status_user_id'), 'sync_status', ['user_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_server_url', sa.String(length=500), nullable=True),
    sa.Column('jellyfin_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('jellyseerr_server_url', sa.String(length=500), nullable=True),
    sa.Column('jellyseerr_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('old_content_months', sa.Integer(), nullable=True),
    sa.Column('min_age_months', sa.Integer(), nullable=True),
    sa.Column('large_movie_size_gb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_sync_status_user_id'), table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_language_exempt_whitelist_user_id'), table_name='language_exempt_whitelist')
    op.drop_index(op.f('ix_language_exempt_whitelist_jellyfin_id'), table_name='language_exempt_whitelist')
    op.drop_table('language_exempt_whitelist')
    op.drop_index(op.f('ix_french_only_whitelist_user_id'), table_name='french_only_whitelist')
    op.drop_index(op.f('ix_french_only_whitelist_jellyfin_id'), table_name='french_only_whitelist')
    op.drop_table('french_only_whitelist')
    op.drop_index(op.f('ix_content_whitelist_user_id'), table_name='content_whitelist')
    op.drop_index(op.f('ix_content_whitelist_jellyfin_id'), table_name='content_whitelist')
    op.drop_table('content_whitelist')
    op.drop_index(op.f('ix_cached_media_items_user_id'), table_name='cached_media_items')
    op.drop_index(op.f('ix_cached_media_items_jellyfin_id'), table_name='cached_media_items')
    op.drop_table('cached_media_items')
    op.drop_index(op.f('ix_cached_jellyseerr_requests_user_id'), table_name='cached_jellyseerr_requests')
    op.drop_index(op.f('ix_cached_jellyseerr_requests_jellyseerr_id'), table_name='cached_jellyseerr_requests')
    op.drop_table('cached_jellyseerr_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
